---

working_directory:
  - "/root/repo"
  - "/tmp/work"

install_packages:
  - autoconf
  - bash-completion.noarch
  - curl.x86_64
  - dstat
  - epel-release
  - gcc.x86_64
  - git.x86_64
  - golang.x86_64
  - jq.x86_64
  - luajit.x86_64
  - lua-devel.x86_64
  - python3.x86_64
  - python3-pip.noarch
  - make.x86_64
  - ncurses-devel.x86_64
  - net-tools.x86_64
  - strace
  - sysstat.x86_64
  - tcpdump
  - wget.x86_64
  - zsh.x86_64

clone_repo_list:
  - {"name": "https://github.com/ryuichi1208/dotfiles.git", "dest": "/root/repo/dotfiles"}
  - {"name": "https://github.com/vim/vim.git", "dest": "/root/repo/vim"}
  - {"name": "https://github.com/junegunn/fzf.git", "dest": "/root/.fzf"}

kernel_parameter:
  - {"name": "net.core.somaxconn", "value": 8192}
  - {"name": "net.core.rmem_max", "value": 16777216}
  - {"name": "net.core.wmem_max", "value": 16777216}
  - {"name": "net.ipv4.tcp_max_syn_backlog", "value": 8192}
  - {"name": "net.ipv4.tcp_fin_timeout ", "value": 5}
  - {"name": "net.ipv4.tcp_syn_retries", "value": 3}
  - {"name": "net.ipv4.tcp_syncookies", "value": 1}
  - {"name": "net.ipv4.ip_local_port_range", "value": "10000 65535"}
  - {"name": "net.ipv4.tcp_tw_reuse", "value": 1}
  - {"name": "net.core.netdev_max_backlog", "value": 65536}
  - {"name": "net.ipv4.tcp_rfc1337", "value": 1}
  - {"name": "net.ipv6.conf.all.disable_ipv6", "value": 1}
  - {"name": "net.ipv6.conf.default.disable_ipv6", "value": 1}
  - {"name": "fs.file-max", "value": 5242880}
  - {"name": "vm.swappiness", "value": 1}
